const comments = [
  {
    kind: "t1",
    data: {
    subreddit_id: "t5_2r7yd",
    approved_at_utc: null,
    author_is_blocked: false,
    comment_type: null,
    awarders: [ ],
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: "text",
    total_awards_received: 0,
    subreddit: "learnprogramming",
    author_flair_template_id: null,
    likes: null,
    replies: {},
    user_reports: [ ],
    saved: false,
    id: "hk8spt5",
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    collapsed_reason_code: null,
    no_follow: false,
    author: "plastikmissile",
    can_mod_post: false,
    created_utc: 1636661490,
    send_replies: true,
    parent_id: "t3_qrtie7",
    score: 629,
    author_fullname: "t2_dk1op",
    approved_by: null,
    mod_note: null,
    all_awardings: [ ],
    collapsed: false,
    body: "For some people, they feel like they're having fun from the very start, others will *never* consider programming fun, while most lie somewhere in between.",
    edited: false,
    top_awarded_type: null,
    author_flair_css_class: null,
    name: "t1_hk8spt5",
    is_submitter: false,
    downs: 0,
    author_flair_richtext: [ ],
    author_patreon_flair: false,
    body_html: `&lt;div class="md"&gt;&lt;p&gt;For some people, they feel like they&amp;#39;re having fun from the very start, others will &lt;em&gt;never&lt;/em&gt; consider programming fun, while most lie somewhere in between.&lt;/p&gt; &lt;/div&gt;`,
    removal_reason: null,
    collapsed_reason: null,
    distinguished: null,
    associated_award: null,
    stickied: false,
    author_premium: false,
    can_gild: true,
    gildings: { },
    unrepliable_reason: null,
    author_flair_text_color: null,
    score_hidden: false,
    permalink: "/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/hk8spt5/",
    subreddit_type: "public",
    locked: false,
    report_reasons: null,
    created: 1636661490,
    author_flair_text: null,
    treatment_tags: [ ],
    link_id: "t3_qrtie7",
    subreddit_name_prefixed: "r/learnprogramming",
    controversiality: 0,
    depth: 0,
    author_flair_background_color: null,
    collapsed_because_crowd_control: null,
    mod_reports: [ ],
    num_reports: null,
    ups: 629
    }
    },
    {
    kind: "t1",
    data: {
    subreddit_id: "t5_2r7yd",
    approved_at_utc: null,
    author_is_blocked: false,
    comment_type: null,
    awarders: [ ],
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: "text",
    total_awards_received: 2,
    subreddit: "learnprogramming",
    author_flair_template_id: null,
    likes: null,
    replies: {},
    user_reports: [ ],
    saved: false,
    id: "hk9296c",
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    collapsed_reason_code: null,
    no_follow: false,
    author: "aintnufincleverhere",
    can_mod_post: false,
    created_utc: 1636665410,
    send_replies: true,
    parent_id: "t3_qrtie7",
    score: 132,
    author_fullname: "t2_ccaki",
    approved_by: null,
    mod_note: null,
    all_awardings: [],
    collapsed: false,
    body: "The fun for me is the puzzle of it. Its not about the pesky details you have to learn. &amp;#x200B; But that's true about a lot of games too. In chess, the pawns can move 2 squares in their first move. I have to know that in order to strategize. **Learning the rules of a game isn't the fun part.**",
    edited: false,
    top_awarded_type: null,
    author_flair_css_class: null,
    name: "t1_hk9296c",
    is_submitter: false,
    downs: 0,
    author_flair_richtext: [ ],
    author_patreon_flair: false,
    body_html: `&lt;div class="md"&gt;&lt;p&gt;The fun for me is the puzzle of it. &lt;/p&gt; &lt;p&gt;Its not about the pesky details you have to learn. &lt;/p&gt; &lt;p&gt;&amp;#x200B;&lt;/p&gt; &lt;p&gt;But that&amp;#39;s true about a lot of games too. In chess, the pawns can move 2 squares in their first move. I have to know that in order to strategize. &lt;strong&gt;Learning the rules of a game isn&amp;#39;t the fun part.&lt;/strong&gt;&lt;/p&gt; &lt;/div&gt;`,
    removal_reason: null,
    collapsed_reason: null,
    distinguished: null,
    associated_award: null,
    stickied: false,
    author_premium: true,
    can_gild: true,
    gildings: {
    gid_1: 1
    },
    unrepliable_reason: null,
    author_flair_text_color: null,
    score_hidden: false,
    permalink: "/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/hk9296c/",
    subreddit_type: "public",
    locked: false,
    report_reasons: null,
    created: 1636665410,
    author_flair_text: null,
    treatment_tags: [ ],
    link_id: "t3_qrtie7",
    subreddit_name_prefixed: "r/learnprogramming",
    controversiality: 0,
    depth: 0,
    author_flair_background_color: null,
    collapsed_because_crowd_control: null,
    mod_reports: [ ],
    num_reports: null,
    ups: 132
    }
    },
    {
    kind: "t1",
    data: {
    subreddit_id: "t5_2r7yd",
    approved_at_utc: null,
    author_is_blocked: false,
    comment_type: null,
    awarders: [ ],
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: "text",
    total_awards_received: 0,
    subreddit: "learnprogramming",
    author_flair_template_id: null,
    likes: null,
    replies: {},
    user_reports: [ ],
    saved: false,
    id: "hk8qq0o",
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    collapsed_reason_code: null,
    no_follow: false,
    author: "_Atomfinger_",
    can_mod_post: false,
    created_utc: 1636660675,
    send_replies: true,
    parent_id: "t3_qrtie7",
    score: 143,
    author_fullname: "t2_mze4j6e",
    approved_by: null,
    mod_note: null,
    all_awardings: [ ],
    collapsed: false,
    body: "Yup. At some point, most of the frustrations go away and the sense of accomplishment increases. There will always be some sort of challenge though.",
    edited: false,
    top_awarded_type: null,
    author_flair_css_class: null,
    name: "t1_hk8qq0o",
    is_submitter: false,
    downs: 0,
    author_flair_richtext: [ ],
    author_patreon_flair: false,
    body_html: `&lt;div class="md"&gt;&lt;p&gt;Yup. At some point, most of the frustrations go away and the sense of accomplishment increases. There will always be some sort of challenge though.&lt;/p&gt; &lt;/div&gt;`,
    removal_reason: null,
    collapsed_reason: null,
    distinguished: null,
    associated_award: null,
    stickied: false,
    author_premium: false,
    can_gild: true,
    gildings: { },
    unrepliable_reason: null,
    author_flair_text_color: null,
    score_hidden: false,
    permalink: "/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/hk8qq0o/",
    subreddit_type: "public",
    locked: false,
    report_reasons: null,
    created: 1636660675,
    author_flair_text: null,
    treatment_tags: [ ],
    link_id: "t3_qrtie7",
    subreddit_name_prefixed: "r/learnprogramming",
    controversiality: 0,
    depth: 0,
    author_flair_background_color: null,
    collapsed_because_crowd_control: null,
    mod_reports: [ ],
    num_reports: null,
    ups: 143
    }
    },
    {
    kind: "t1",
    data: {
    subreddit_id: "t5_2r7yd",
    approved_at_utc: null,
    author_is_blocked: false,
    comment_type: null,
    awarders: [ ],
    mod_reason_by: null,
    banned_by: null,
    author_flair_type: "text",
    total_awards_received: 0,
    subreddit: "learnprogramming",
    author_flair_template_id: null,
    likes: null,
    replies: {},
    user_reports: [ ],
    saved: false,
    id: "hk8s9bl",
    banned_at_utc: null,
    mod_reason_title: null,
    gilded: 0,
    archived: false,
    collapsed_reason_code: null,
    no_follow: false,
    author: "carcigenicate",
    can_mod_post: false,
    created_utc: 1636661300,
    send_replies: true,
    parent_id: "t3_qrtie7",
    score: 41,
    author_fullname: "t2_goyne",
    approved_by: null,
    mod_note: null,
    all_awardings: [ ],
    collapsed: false,
    body: `I've been writing code for ~14 years because I think it's fun. The only money I've ever gotten from programming was from tutoring, so I do it entirely for the fun of it. I don't think there's ever been a point where I didn't find it fun. Arguably, it's actually become less fun and more stressful as time goes on, because now on top of writing code, I'm also trying to get my code running on a cloud platform and other "exrta stuff".`,
    edited: false,
    top_awarded_type: null,
    author_flair_css_class: null,
    name: "t1_hk8s9bl",
    is_submitter: false,
    downs: 0,
    author_flair_richtext: [ ],
    author_patreon_flair: false,
    body_html: `&lt;div class="md"&gt;&lt;p&gt;I&amp;#39;ve been writing code for ~14 years because I think it&amp;#39;s fun. The only money I&amp;#39;ve ever gotten from programming was from tutoring, so I do it entirely for the fun of it. I don&amp;#39;t think there&amp;#39;s ever been a point where I didn&amp;#39;t find it fun.&lt;/p&gt; &lt;p&gt;Arguably, it&amp;#39;s actually become less fun and more stressful as time goes on, because now on top of writing code, I&amp;#39;m also trying to get my code running on a cloud platform and other &amp;quot;exrta stuff&amp;quot;.&lt;/p&gt; &lt;/div&gt;`,
    removal_reason: null,
    collapsed_reason: null,
    distinguished: null,
    associated_award: null,
    stickied: false,
    author_premium: false,
    can_gild: true,
    gildings: { },
    unrepliable_reason: null,
    author_flair_text_color: null,
    score_hidden: false,
    permalink: "/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/hk8s9bl/",
    subreddit_type: "public",
    locked: false,
    report_reasons: null,
    created: 1636661300,
    author_flair_text: null,
    treatment_tags: [ ],
    link_id: "t3_qrtie7",
    subreddit_name_prefixed: "r/learnprogramming",
    controversiality: 0,
    depth: 0,
    author_flair_background_color: null,
    collapsed_because_crowd_control: null,
    mod_reports: [ ],
    num_reports: null,
    ups: 41
    },
  },
]

export default comments;