export const posts = [
{
author: "michael0x2a",
author_fullname: "t2_aoqnb",
created: 1490569654,
created_utc: 1490569654,
id: "61oly8",
name: "t3_61oly8",
num_comments: 14,
num_crossposts: 8,
permalink: "/r/learnprogramming/comments/61oly8/new_read_me_first/",
score: 828,
selftext: "# Welcome to /r/learnprogramming!\n\n## Quick start:\n\n1. New to programming? Not sure how to start learning? See [FAQ - Getting started][faq-start].\n2. Have a question? Our [FAQ][faq] covers many common questions; check that first. Also try searching old posts, either [via google][google] or via reddit's search.\n3. Your question isn't answered in the FAQ? Please read the following:\n\n## Getting debugging help\n\nIf your question is about code, make sure it's **specific** and **provides all information up-front**. Here's a checklist of what to include:\n\n1. A [**concise but descriptive title**][debugging-title].\n2. A [**good description**][debugging-description] of the problem.\n4.  A [**minimal**, **easily runnable**][debugging-posting], and [**well-formatted**][debugging-formatting] program that demonstrates your problem.\n5. The output you expected and what you got instead. If you got an error, include the **full** error message.\n\nDo your best to solve your problem before posting. The quality of the answers will be proportional to the amount of effort you put into your post. Note that title-only posts are automatically removed.\n\nAlso see [our full posting guidelines][debugging] and the [subreddit rules][rules]. After you post a question, **DO NOT** delete it!\n\n## Asking conceptual questions\n\nAsking conceptual questions is ok, but please check [our FAQ][faq] and search older posts first.\n\nIf you plan on asking a question similar to one in the FAQ, explain what exactly the FAQ didn't address and clarify what you're looking for instead. See our full guidelines on [asking conceptual questions][conceptual] for more details.\n\n## Subreddit rules\n\nPlease read [our rules][rules] and [other policies][policies] before posting. If you see somebody breaking a rule, report it! Reports and PMs to the mod team are the quickest ways to bring issues to our attention.\n\n\n  [faq-start]: https://www.reddit.com/r/learnprogramming/wiki/faq#wiki_getting_started\n  [faq]: https://www.reddit.com/r/learnprogramming/wiki/faq\n  [google]: https://www.google.com/#q=site:reddit.com%2Fr%2Flearnprogramming\n  [wiki]: https://www.reddit.com/r/learnprogramming/wiki/index\n  [debugging]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_getting_debugging_help\n  [debugging-title]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_writing_a_good_title\n  [debugging-description]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_writing_a_good_description_of_the_problem\n  [debugging-posting]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_posting_code\n  [debugging-formatting]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_formatting_code\n  [conceptual]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_asking_conceptual_questions\n  [rules]: https://www.reddit.com/r/learnprogramming/about/rules\n  [policies]: https://www.reddit.com/r/learnprogramming/wiki/index#wiki_rules",
selftext_html: "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;h1&gt;Welcome to &lt;a href=\"/r/learnprogramming\"&gt;/r/learnprogramming&lt;/a&gt;!&lt;/h1&gt;\n\n&lt;h2&gt;Quick start:&lt;/h2&gt;\n\n&lt;ol&gt;\n&lt;li&gt;New to programming? Not sure how to start learning? See &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/faq#wiki_getting_started\"&gt;FAQ - Getting started&lt;/a&gt;.&lt;/li&gt;\n&lt;li&gt;Have a question? Our &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/faq\"&gt;FAQ&lt;/a&gt; covers many common questions; check that first. Also try searching old posts, either &lt;a href=\"https://www.google.com/#q=site:reddit.com%2Fr%2Flearnprogramming\"&gt;via google&lt;/a&gt; or via reddit&amp;#39;s search.&lt;/li&gt;\n&lt;li&gt;Your question isn&amp;#39;t answered in the FAQ? Please read the following:&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;h2&gt;Getting debugging help&lt;/h2&gt;\n\n&lt;p&gt;If your question is about code, make sure it&amp;#39;s &lt;strong&gt;specific&lt;/strong&gt; and &lt;strong&gt;provides all information up-front&lt;/strong&gt;. Here&amp;#39;s a checklist of what to include:&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;A &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_writing_a_good_title\"&gt;&lt;strong&gt;concise but descriptive title&lt;/strong&gt;&lt;/a&gt;.&lt;/li&gt;\n&lt;li&gt;A &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_writing_a_good_description_of_the_problem\"&gt;&lt;strong&gt;good description&lt;/strong&gt;&lt;/a&gt; of the problem.&lt;/li&gt;\n&lt;li&gt; A &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_posting_code\"&gt;&lt;strong&gt;minimal&lt;/strong&gt;, &lt;strong&gt;easily runnable&lt;/strong&gt;&lt;/a&gt;, and &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_formatting_code\"&gt;&lt;strong&gt;well-formatted&lt;/strong&gt;&lt;/a&gt; program that demonstrates your problem.&lt;/li&gt;\n&lt;li&gt;The output you expected and what you got instead. If you got an error, include the &lt;strong&gt;full&lt;/strong&gt; error message.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Do your best to solve your problem before posting. The quality of the answers will be proportional to the amount of effort you put into your post. Note that title-only posts are automatically removed.&lt;/p&gt;\n\n&lt;p&gt;Also see &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_getting_debugging_help\"&gt;our full posting guidelines&lt;/a&gt; and the &lt;a href=\"https://www.reddit.com/r/learnprogramming/about/rules\"&gt;subreddit rules&lt;/a&gt;. After you post a question, &lt;strong&gt;DO NOT&lt;/strong&gt; delete it!&lt;/p&gt;\n\n&lt;h2&gt;Asking conceptual questions&lt;/h2&gt;\n\n&lt;p&gt;Asking conceptual questions is ok, but please check &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/faq\"&gt;our FAQ&lt;/a&gt; and search older posts first.&lt;/p&gt;\n\n&lt;p&gt;If you plan on asking a question similar to one in the FAQ, explain what exactly the FAQ didn&amp;#39;t address and clarify what you&amp;#39;re looking for instead. See our full guidelines on &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_asking_conceptual_questions\"&gt;asking conceptual questions&lt;/a&gt; for more details.&lt;/p&gt;\n\n&lt;h2&gt;Subreddit rules&lt;/h2&gt;\n\n&lt;p&gt;Please read &lt;a href=\"https://www.reddit.com/r/learnprogramming/about/rules\"&gt;our rules&lt;/a&gt; and &lt;a href=\"https://www.reddit.com/r/learnprogramming/wiki/index#wiki_rules\"&gt;other policies&lt;/a&gt; before posting. If you see somebody breaking a rule, report it! Reports and PMs to the mod team are the quickest ways to bring issues to our attention.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
title: "New? READ ME FIRST!",
ups: 828,
upvote_ratio: 0.98,
url: "https://www.reddit.com/r/learnprogramming/comments/61oly8/new_read_me_first/",
}
,
{
author: "hikejohn",
author_fullname: "t2_fz8pkv6r",
created: 1636707131,
created_utc: 1636707131,
id: "qs752g",
name: "t3_qs752g",
num_comments: 58,
num_crossposts: 0,
permalink: "/r/learnprogramming/comments/qs752g/how_to_sit_at_pc_for_long_periods_of_time/",
score: 131,
selftext: "How do guys who say they program 8 hours a day manage to sit there all day? I feel like doing something else after 1 hour of being on even when doing something I somewhat enjoy like gaming... I don't know if it is because I have low attention span or uncomfortable cheap office chair and desk or maybe a combo of both.",
selftext_html: "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;How do guys who say they program 8 hours a day manage to sit there all day? I feel like doing something else after 1 hour of being on even when doing something I somewhat enjoy like gaming... I don&amp;#39;t know if it is because I have low attention span or uncomfortable cheap office chair and desk or maybe a combo of both.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
title: "How to sit at PC for long periods of time?",
ups: 131,
upvote_ratio: 0.94,
url: "https://www.reddit.com/r/learnprogramming/comments/qs752g/how_to_sit_at_pc_for_long_periods_of_time/",
}
,{
author: "Inconstant_Moo",
author_fullname: "t2_98m2bpc9",
created: 1636661217,
created_utc: 1636661217,
id: "qrtrv1",
name: "t3_qrtrv1",
num_comments: 25,
num_crossposts: 0,
permalink: "/r/learnprogramming/comments/qrtrv1/why_you_should_search_by_new_now_and_then/",
score: 578,
selftext: "I search this subreddit by new a lot, and that's where you find people with technical problems.\n\nSometimes, I see people here complaining that this subreddit has turned into motivational posts. You could search by new, and you'd find otherwise.\n\nYou could see people floundering and in need of help, and you could reach out a helping hand.\n\nYou can sharpen your own skills at reading and debugging code by helping them solve their problems.\n\nYou can learn something yourself.",
selftext_html: "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I search this subreddit by new a lot, and that&amp;#39;s where you find people with technical problems.&lt;/p&gt;\n\n&lt;p&gt;Sometimes, I see people here complaining that this subreddit has turned into motivational posts. You could search by new, and you&amp;#39;d find otherwise.&lt;/p&gt;\n\n&lt;p&gt;You could see people floundering and in need of help, and you could reach out a helping hand.&lt;/p&gt;\n\n&lt;p&gt;You can sharpen your own skills at reading and debugging code by helping them solve their problems.&lt;/p&gt;\n\n&lt;p&gt;You can learn something yourself.&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
title: "Why you should search by New now and then",
ups: 578,
upvote_ratio: 0.96,
url: "https://www.reddit.com/r/learnprogramming/comments/qrtrv1/why_you_should_search_by_new_now_and_then/",
},
{
author: "waydethegreat",
author_fullname: "t2_3dot2w8l",
created: 1636660501,
created_utc: 1636660501,
id: "qrtie7",
name: "t3_qrtie7",
num_comments: 271,
num_crossposts: 0,
permalink: "/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/",
score: 483,
selftext: "I’m a month into a full stack online course now and honestly it’s just stressing me out and making me frustrated. Is there a point where it actually becomes enjoyable? Or do some people just love the constant frustration and challenges?",
selftext_html: "&lt;!-- SC_OFF --&gt;&lt;div class=\"md\"&gt;&lt;p&gt;I’m a month into a full stack online course now and honestly it’s just stressing me out and making me frustrated. Is there a point where it actually becomes enjoyable? Or do some people just love the constant frustration and challenges?&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;",
title: "Does programming ever become fun?",
ups: 483,
upvote_ratio: 0.92,
url: "https://www.reddit.com/r/learnprogramming/comments/qrtie7/does_programming_ever_become_fun/",
}]